### ISSUE TITLE
Time offset not being defined

### ISSUE THREAD

**Issue by cscashby** [astrilchuk/sd2xmltv#13]
During British Summer Time, listings do not have a time offset output, leading to listings being recorded an hour early.

A time offset capability needs to be introduced (as defined in http://wiki.xmltv.org/index.php/XmltvCapabilities)

**Comment by astrilchuk** [comment]
The time in the output is UTC so I'm not why clear why the offset needs to be included (other than perhaps adding +0000).  Have you set your OS's timezone?

**Comment by cscashby** [comment]
Yes, timezone is set to Europe/London.  It may need the +0000 but I agree with you, it's weird.

If you could point me to the change to make to include the offset I can run some tests and send a pull request? Thanks!

**Comment by astrilchuk** [comment]
You can change line 45 and 46 of common.py in xmltv to something like this:

``` python
            u"start": unicode(start_time.strftime("%Y%m%d%H%M%S") + "+0000"),
            u"stop": unicode(stop_time.strftime("%Y%m%d%H%M%S") + "+0000"),
```

Thanks!

**Comment by cscashby** [comment]
Much appreciated. I'll have a play and get back to you.

**Comment by astrilchuk** [comment]
Have you had a chance to test with the timezone offset?  I'm very curious if it sorts out the issue you were seeing.

**Comment by cscashby** [comment]
No, this still doesn't work. So as an example - from atlas.metabroadcast.com, eggheads starts today 30th May 1715 BST (GMT+1).  It shows in TVHeadend as 1615 with the sd2xmltv data being loaded via a socket.  /etc/timezone is set to Europe/London and the tv_grab_atlas, and EIT data both show the episode as starting at 1715.

**Comment by astrilchuk** [comment]
The xmltv output shows Eggheads starting at 16:15 UTC on BBC2 and www.tvguide.co.uk shows it starting at 17:15 BST.  16:15 UTC is 17:15 BST so it appears that the data from Schedules Direct and sd2xmltv is correct.  It seems this may be an issue with tvheadend.  Perhaps try deleting the epgdb.v2 database for tvheadend and reloading.  Beyond that I'm not sure what else to suggest.

``` xml
<programme channel="I2.17154.schedulesdirect.org" start="20160530161500" stop="20160530164500">
 <title>Eggheads</title>
 <episode-num system="dd_progid">EP01260922.0880</episode-num>
 <episode-num system="xmltv_ns">16.63.</episode-num>
 <desc>Series; New; S17E64</desc>
 <icon src="https://json.schedulesdirect.org/20141201/image/assets/p230279_b_v3_ac.jpg" />
</programme>
```

**Comment by cscashby** [comment]
I'll run tv_grab_uk_rt and see if I can get the same programme and compare. It was working with tv_grab_uk_atlas previously but they've pulled their API. Thanks for your help. I'll keep digging!

**Comment by astrilchuk** [comment]
You mentioned EIT - there is a EIT time offset setting in tvheadend under Configuration > DVB Inputs > Networks.

**Comment by cscashby** [comment]
Yes, I saw that. I was running TVHeadend 3.x, I've updated to latest and will rerun some tests. Bear with me, as it could take a few days to get new data. Thanks for all your support thus far.

**Comment by astrilchuk** [comment]
Ok, no problem.

Just fyi, the way I would go about testing this is to create a custom xmltv file with a single channel and single show.  Then I would stop tvheadend, delete epgdb.v2, and restart (important to follow that order).  Load your custom xmltv file and check the times.  If the times are off, submit a ticket with tvheadend with your findings.

Good luck!

In the meantime I'm going to close this issue since it doesn't (currently) appear to be an issue with sd2xmltv.
