### ISSUE TITLE
Add channel icon functionality

### ISSUE THREAD

**Issue by astrilchuk** [astrilchuk/sd2xmltv#14]
Compatibility with various skins needs to be addressed.  Most icons have transparency and will not display properly on some skins.  Perhaps programmatically adding a grey background will address this issue.

**Comment by edit4ever** [comment]
Not sure how to do that without editing the skin.  The skin just needs a simple css tweak like to add a second background to the icon, something like `radial-gradient(circle, white, black)` would be versatile across a number of skins.  I don't see how to add that on this end.

**Comment by astrilchuk** [comment]
Cleaning up old issues - will revisit when (if) channel icons are standardized.
