### ISSUE TITLE
Unable to add a lineup

### ISSUE THREAD

**Issue by bingh0** [astrilchuk/sd2xmltv#15]
Hello, I'm trying to use your script in Libreelec/Openelec and encounter the following error.
# python sd2xml.py -u ### -p ### -m

Manage Account Options:
1. List subscribed lineups
2. Add lineup
3. Remove lineup
4. List lineup channels.

Choose an option or 'x' to exit.

> 2

Add Lineup

Enter 5-digit zip or postal code or 'x' to cancel:

> 12345 {obviously not real}
> 2016-08-31 16:47:37,318 root                                ERROR    {"response":"NO_LINEUPS","code":4102,"serverID":"20141201.web.2","message":"No lineups have been added to this account.","datetime":"2016-08-31T21:47:37Z"}
> Traceback (most recent call last):
>   File "sd2xmltv.py", line 362, in <module>
>     main()
>   File "sd2xmltv.py", line 356, in main
>     app.manage()
>   File "sd2xmltv.py", line 62, in manage
>     self._sd.manage()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 298, in manage
>     self._add_lineup()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 330, in _add_lineup
>     subscribed_lineups = self.get_subscribed_lineups()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 70, in get_subscribed_lineups
>     lineups_dict = api.get_subscribed_lineups(self._token)
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/api.py", line 70, in get_subscribed_lineups
>     if "response" in response and response["response"] == "NO_LINEUPS":
> TypeError: string indices must be integers, not str

**Comment by astrilchuk** [comment]
That's an odd message to be returned from Schedules Direct.  Can you try the 'develop' branch from the repo?  It has the latest code and I know I've made a few changes regarding adding lineups.

**Comment by bingh0** [comment]
Hi,

I just tried development branch and deleted all my lineups (to start from
scratch) and get the same error. If I use xmltv directly to create the
first lineup, everything works great. This only happens when there isn't an
existing lineup in the JSON service.

Manage Account Options:
1. List subscribed lineups
2. Add lineup
3. Remove lineup
4. List lineup channels.

Choose an option or 'x' to exit.

> 2

Add Lineup

Enter 3-character country/region code or 'x' to cancel:

> USA
> Enter zip/postal code or 'x' to cancel:
> 12345 {not real}
> 2016-09-01 10:07:00,109 root                                ERROR
>  {"response":"NO_LINEUPS","code":4102,"serverID":"20141201.web.2","message":"No
> lineups have been added to this account.","datetime":"2016-09-01T15:06:59Z"}
> Traceback (most recent call last):
>   File "./sd2xmltv.py", line 370, in <module>
>     main()
>   File "./sd2xmltv.py", line 364, in main
>     app.manage()
>   File "./sd2xmltv.py", line 58, in manage
>     self._sd.manage()
>   File
> "/Users/biho/Desktop/sd2xmltv-develop/kodi/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py",
> line 295, in manage
>     self._add_lineup()
>   File
> "/Users/biho/Desktop/sd2xmltv-develop/kodi/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py",
> line 328, in _add_lineup
>     subscribed_lineups = self.get_subscribed_lineups()
>   File
> "/Users/biho/Desktop/sd2xmltv-develop/kodi/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py",
> line 71, in get_subscribed_lineups
>     lineups_dict = api.get_subscribed_lineups(self._token)
>   File
> "/Users/biho/Desktop/sd2xmltv-develop/kodi/tools.module.sd2xmltv/libschedulesdirect/api.py",
> line 81, in get_subscribed_lineups
>     if "response" in response and response["response"] == "NO_LINEUPS":
> TypeError: string indices must be integers, not str

**Comment by bingh0** [comment]
Thank you!
