### ISSUE TITLE
Does tvheadend actually read all those <icon src= > in <programme>?

### ISSUE THREAD

**Issue by bingh0** [astrilchuk/sd2xmltv#17]
Hi, sorry to keep pestering, this addon is great at downloading schedules direct, but have you been able to view any of the <icon src= xxx.jpg> in <programme> within tvheadend? I'm running LibreElec alpha with tvheadend 4.1 (build 2195) and I see the information in xmltv.xml but not in tvheadend or Kodi. Does tvheadend even support URL or only local files?

```
<programme channel="I2.1.20454.schedulesdirect.org" start="20160902000000" stop="20160902003100">
 <icon src="https://s3.amazonaws.com/schedulesdirect/assets/p185554_b_v3_al.jpg" />
</programme>
```

**Comment by astrilchuk** [comment]
Hi, yes, the programme icons are passed to Kodi via tvheadend (I'm running LibreElec alpha nightlies and the master branch of tvheadend).  The Confluence skin displayed the icons in the guide display and the program info dialog box.  Unfortunately the new Estuary skin only displays the icons when you select the program info dialog box.
