### ISSUE TITLE
Unable to pull lineup or add lineup 

### ISSUE THREAD

**Issue by natetanr** [astrilchuk/sd2xmltv#18]
When I ssh into openelec on my rasberry pi and try to run the schedules direct script I get a datetime warning and unable to add a lineup see the following....

python sd2xmltv.py -u username -p password -m
2016-10-07 13:29:26,949 **main**                            INFO     Getting SchedulesDirect token.
2016-10-07 13:29:27,487 **main**                            INFO     Getting SchedulesDirect status.
2016-10-07 13:29:28,001 root                                WARNING  Key(s) not processed for Status: datetime
2016-10-07 13:29:28,002 **main**                            INFO     Account will expire on 2016-12-04 06:03:16 (57 days).
2016-10-07 13:29:28,004 **main**                            INFO     SchedulesDirect last update at 2016-10-07 03:46:00 (9 hours 43 minutes ago).
2016-10-07 13:29:28,005 **main**                            INFO     Message: No known issues.

Manage Account Options:
1. List subscribed lineups
2. Add lineup
3. Remove lineup
4. List lineup channels.

Choose an option or 'x' to exit.

> 2

Add Lineup

Enter 5-digit zip or postal code or 'x' to cancel:

> 84101
> 2016-10-07 13:29:51,285 root                                ERROR    {"response":"NO_LINEUPS","code":4102,"serverID":"20141201.web.2","message":"No lineups have been added to this account.","datetime":"2016-10-07T13:29:51Z"}
> Traceback (most recent call last):
>   File "sd2xmltv.py", line 362, in <module>
>     main()
>   File "sd2xmltv.py", line 356, in main
>     app.manage()
>   File "sd2xmltv.py", line 62, in manage
>     self._sd.manage()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 298, in manage
>     self._add_lineup()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 330, in _add_lineup
>     subscribed_lineups = self.get_subscribed_lineups()
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/schedulesdirect.py", line 70, in get_subscribed_lineups
>     lineups_dict = api.get_subscribed_lineups(self._token)
>   File "/storage/.kodi/addons/tools.module.sd2xmltv/libschedulesdirect/api.py", line 70, in get_subscribed_lineups
>     if "response" in response and response["response"] == "NO_LINEUPS":
> TypeError: string indices must be integers, not str

**Comment by astrilchuk** [comment]
Hi, I believe that was fixed in the develop branch of the repository.  Can you grab that version and give it a try?  I'll try to get develop merged with master this weekend if not today.

Thanks

**Comment by natetanr** [comment]
That worked, Thanks!!

**Comment by natetanr** [comment]
That worked! Thanks!
