### ISSUE TITLE
logging.ini missing in kodi build

### ISSUE THREAD

**Issue by edit4ever** [astrilchuk/sd2xmltv#19]
This issue was reported on the LE forum after I posted the kodi build there:

[https://forum.libreelec.tv/thread-440-post-15762.html#pid15762](url)

I'm guessing just a simple update to the build_kodi_addon file?

**Comment by astrilchuk** [comment]
I'm not clear on why the logging.ini file would be missing for some people.  Or am I not understanding the issue?

**Comment by jcromero** [comment]
@astrilchuk Perhaps because you are not copying it in the build_kodi_addon script?

**Comment by astrilchuk** [comment]
Doh! @jcromero, you are correct.  The addon build script was only including *.py files from the root folder.  I have explicitly included the logging.cfg file now and incremented the addon version number.
