### ISSUE TITLE
export data to xmltv file

### ISSUE THREAD

**Issue by edit4ever** [astrilchuk/sd2xmltv#22]
Currently you're embedding most of the program metadata into the description field.  It would be appropriate to also export those data fields into the xmltv.xml so the data can be read by the pvr backend.

Each piece of data from the sd download has a place in the xmltv.xml file - original air date or movie date, credits, categories, ratings (tv and star), subtitles, video, audio - it would be nice to include these in the xmltv output.

I realize your initial intent is to deal with the limitations of tvheadend - but tvh improvements (and other pvrs) can handle the data from the xmltv.xml file.  Hopefully it's not too hard to add the code to output that info.  Thanks!

**Comment by astrilchuk** [comment]
Unfortunately I will not be making further improvements to the application beyond bug fixes and covering API changes.  sd2xmltv serves my needs and there is no benefit to extending it beyond it's current feature set.  I would encourage you to fork the application and add whatever changes suit your needs.
