### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by bonelifer** [astrilchuk/sd2xmltv#6]
Are you still working on this?

**Comment by astrilchuk** [comment]
Hi William,

Yes, sd2xmltv is very much alive - the current code should work just fine.
Having said that, I'm working on an update which will include links to
artwork in the xml output.  The update should be out later this month.

Adrian

**Comment by edit4ever** [comment]
Is it possible to compile this to work on Raspberry Pi 2/3 running openelec or libreelec??
