### ISSUE TITLE
Not an issue - just a thank you!

### ISSUE THREAD

**Issue by edit4ever** [astrilchuk/sd2xmltv#7]
Wasn't sure where else to write this -- but thank you for creating this!  This addon needs to get into the standard Kodi repository.  At the very least - it needs to be in the LibreELEC and Openelec repositories.  This really solves an issue with EPG in North America and running a grabber on the same machine that TVheadend is on!!

Is there a way to help out with the genre/category section?

Also - definitely looking forward to having the icon pull work as well - that seems to work for mc2xml which is what I had been using before finding your great work!

**Comment by astrilchuk** [comment]
Thank you very much for the compliments - it's always nice to hear the app is working well for others.

Regarding the genre/category section - you are more than welcome to submit a pull request (or even submit an issue with the mappings you'd like to see).  Keep in mind that the categories are currently targeted towards the (unfortunately) hardcoded categories in tvheadend.  Also note that there isn't always a one-to-one mapping between categories so I tried to cover the major ones.

I would ultimately like to make the category mapping configurable but that would a feature for down the road (unless there is high demand for it).

**Comment by astrilchuk** [comment]
Regarding the new version of sd2xml - I'll try to push it up this week.  It's been in a 97% done state since February but I think it's complete enough to let it out into the wild while I polish it off.

**Comment by edit4ever** [comment]
As an FYI, I've chatted with the folks at Tvh and they are looking to rework the category/content code so that it aligns with the newer 3 level specs in the DVB standard.  You can see the thread here:

[https://tvheadend.org/issues/3753#change-18667](url)

As this gets worked in, you should be able to change the the sd2xmltv code to just pass through the existing genre lists and then Tvh will grab those categories and display them in the epg. You're solution was a great workaround for the way the Tvh was hard coded - but fortunately going forward it will not be necessary!  :-)

Thank again for the great work on this - I'v mentioned it on both the kodi and the LibreELEC forums.  You should probably submit to kodi to have the addon added to the repo.  Maybe after we test your new release.

**Comment by edit4ever** [comment]
Happy to test your new version if you want to send it to me or put it up.

**Comment by astrilchuk** [comment]
Ok, have at it!  There are more improvements to come but it's complete enough for you to test it.

**Comment by edit4ever** [comment]
Nicely done!  I had to hash out the hdhomerun info in line 10 of the sd2xmltv.py file as I don't have an hdhomerun and it seems like the resource was missing keeping it from running.  Wasn't sure if this was something that you hadn't completed yet - but since I don't need it I just took it out.

The program icon function is working great.  Tested on the Titan skin without the skin's epg artwork grabber turned on.  It pulled the icon info from the xmltv file and displayed it perfectly in the bottom right corner of the epg.

BTW for my lineup, the channel icon is not functioning.  The icon url info for the channel does not appear in the xmltv file.  I know the data is available and in the cache db but it looks like the program is not outputting the channel icon line.  Not sure if you're seeing something different.  Here are the only lines being output for channel:

`<channel id="I39.1.21213.schedulesdirect.org">
 <display-name>39.1 KNSDDT</display-name>
 <display-name>39.1</display-name>
 <display-name>40 KNSDDT fcc</display-name>
 <display-name>KNSDDT</display-name>
 <display-name>KNSDDT (KNSD-DT)</display-name>
</channel>
`

It would also be good to include the "afiliate" data as a display-name as some epgs can display that info as well.

As an FYI, Tvheadend will make the genre changes in version 4.4 so for now, you're mappings are good- although I found that enabling the full set of strings to be included works as well.  (I enabled the code you had in there already in addition to the mappings!)

Finally, just a thought for the kodi addon part...how hard would it be to work the whitelist feature into the configure section of the addon?  Maybe pull the channel list from the channel manager in kodi (which it gets from tvheadend) and use the "active" channels as the whitelist for the schedules direct feed.  

This addon has a lot of potential to fill a big need for those who want a good epg in North America.  Thank you again for your efforts!

**Comment by astrilchuk** [comment]
Regarding commenting out the hdhomerun line - I think you may not have pulled the libhdhomerun folder from the repo.  Double-check that you have that folder including the contents.

As for the channel icons, I have intentionally not included them due a number of issues.  Some are transparent, some are not, and others won't download.  I will briefly try again to use the icons but I don't want to go down the road which could become a support nightmare for me (or a headache for the users).

I think the channel manager is a good idea though I don't know how much work would be involved.  Unfortunately I think the priority for that feature would be fairly low unless I find the development of it somewhat straight forward.

**Comment by edit4ever** [comment]
Sorry - I was typing the edit about the affiliate data to my previous post while you were commenting!

I'll check for the libhdhomerun folder and add it if it was missing.

Thanks for the info on the channel icons.  They seem to work ok when I pull them with mc2xml - although I agree that some of the logos aren't great for a dark background.  A user can change them if they prefer, but this at least starts the process of having them.  I did notice that not all channels have icon urls (I receive a number of Mexico stations that don't have them) but it didn't seem to cause a problem for me.

Totally understand about the channel manager work - let me know if there is anything I can do to help.  Unfortunately, I'm not an experienced coder, but I'm willing to dig into something if needed.  And thanks again for your efforts!

Are you considering adding this to the kodi addon repo?  I think others would very much appreciate this.  If not the full kodi repo - the folks at LibreELEC would likely appreciate it.

**Comment by edit4ever** [comment]
As an FYI - the libhdhomerun issue was due to the fact that I compiled as a kodi addon and I didn't realize that you hadn't updated that build file.  Maybe a quick update to that file and a version bump to 0.1.1?

**Comment by astrilchuk** [comment]
Did you want to submit a pull request for that? :-)  What better way to get involved? If not, I can certainly bump that version.

**Comment by edit4ever** [comment]
Let me give that a try later today.  I'm new to using git, but think I understand enough to get started and this seems like a great project to work on.  Thanks for letting me chip in. :-)

**Comment by astrilchuk** [comment]
Thanks for the pull request!  Every little bit helps.  With regards to getting the app added to the addon repo, I hadn't given it too much thought.  I run my tvheadend instance on a complete separate Raspberry Pi so I can upgrade and downgrade at will.  I'll try to determine how much work is involved and make a decision on it.

**Comment by edit4ever** [comment]
No worries on the repo - happy to help out there as well if you like.

Also, if you do have the code changes available for the channel icon available - I'd love to test those.  Maybe you could just put that in the develop branch so your other users don't have issues.

**Comment by astrilchuk** [comment]
If you take a look at the sd2xmltv.py file there's a function called _export_icons() which I was using to test downloading channel icons.  You pass it a list of station objects and it will attempt to download the icons.  I was originally thinking it would be something you could run once as a command line parameter.  It would download the files into a specified directory and do a file:// link from there.

**Comment by edit4ever** [comment]
Is that because you don't like the logos that schedules direct provides?  An end user can always override the logo that is listed in the xmltv by using options in kodi, ttvheadend or another backend.  It just seemed like an easy starting point to grab the channel icon url from the schedules direct feed and add it to the xmltv file that is created.  As an FYI - this worked very well for my with mc2xml.  Of course, many of those logos are dark and depending on the skin your using - you might choose a different logo.

**Comment by astrilchuk** [comment]
I'm going to close this issue and open a new one specifically for adding channel icon functionality.  I'd still need to determine how best to handle the transparency and compatibility for various skins.
