### ISSUE TITLE
Is it possible to add "new" notification to data?

### ISSUE THREAD

**Issue by edit4ever** [astrilchuk/sd2xmltv#8]
I believe the common usage is to use an asterik \* to mark new programs.  Is there a way to enable this option?

***\* you can close this...I've noticed that the "New" information is being passed to the XMLTV file.  The issue is with Tvheadend not reading that info correctly.

**Comment by astrilchuk** [comment]
If there is an issue with tvheadend I'd be happy to submit a bug report with them.  It would be easy to add the asterisk to the title/episode title but I'd rather see that done "out-of-band".

I did notice that the hdhomerun pvr client (not the official one) was showing "new" asterisk in kodi.  I'd like  to determine if tvheadend can provide that flag via the pvr api.

**Comment by astrilchuk** [comment]
Closing as this information is provided via the previously-shown tag.
